project_name: ai-fusion-cgyro-nn
model:
  bal-train:
    command: >-
      [](git submodule add https://github.com/Rose-STL-Lab/Zihao-s-Toolbox.git src/toolbox; make download file=tglf_sumf_data_major_perturb/;) python src/train.py -cn <cn> dataset=SR_small dump_dir=<dump-dir> model.latent_dim=256 model.hidden_layer=4 model.num_resnet=4 project=<project> board=True full_eval=True plot=False dataset.dataset_root="./tglf_sumf_data_major_perturb/" batch=480 steps_per_epoch=1000 loss_freq=1000 save_freq=10000 plot_freq=10000 time_freq=1000 time_warm=100 accumulation_steps=1000 opt.warmup_steps=20000 opt.decay_steps=200000 model.apply_asinh_accumulate=<asinh_accumulate> model.normalize_mse_loss=<normalize_mse_loss> opt.random_loss=<random_loss>; s5cmd cp "<dump-dir>/*" s3://ai-fusion-ga/results/<dump-dir>/major_perturb/
    gpu_count: 1
    memory: 30
    cpu_count: 4
    ephemeral_storage: 200
dataset:
  initial-dataset:
    hparam:
      # Launch will automatically consider all combinations of hparam
      # hparam preceded by _ will NOT appear in the job name
      # If your hparam contain special characters, you must _ them
      _dump-dir: ["./fixed-getpred-runs-asinhaccu"]
      _project: ["SR"]
      _cn: [SR]
      _asinh_accumulate: [True]
      _normalize_mse_loss: [False]
      _random_loss: [False]
run:
  dataset: [initial-dataset]
  model: [bal-train]